name: samsung_galaxy_in_app_purchase
description: A Flutter plugin that facilitates the integration of Samsung Galaxy In-App Purchase (IAP) SDK with your Flutter application, enabling seamless in-app purchase functionality for Samsung Galaxy devices.
repository: https://github.com/Genopets/samsung_galaxy_in_app_purchase
version: 0.5.0
homepage:

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.genopets.plugins.samsung_galaxy_in_app_purchase
        pluginClass: GalaxyIapPlugin

topics:
  - in-app-purchase
  - payment
  - samsung
  - galaxy

screenshots:
  - description: 'Displaying the list of products available for purchase'
    path: doc/flow1.jpeg
  - description: 'Galaxy test mode acknowledgement dialog'
    path: doc/flow2.jpeg
  - description: 'Galaxy IAP checkout dialog'
    path: doc/flow3.jpeg
  - description: 'Completing payment...'
    path: doc/flow4.jpeg
  - description: 'Purchase successful!'
    path: doc/flow5.jpeg
  - description: 'Your purchase items arrived!'
    path: doc/flow6.jpeg
  - description: 'Example of in-app purchase complete flow'
    path: doc/example.gif
